version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn bona_blog.wsgi:application --bind 0.0.0.0:8001"
    volumes:
      - ./staticfiles:/code/staticfiles  # Mount local staticfiles directory
      - ./media:/code/media  
    env_file:
      - .env
    network_mode: "host"

volumes:
  static_volume:
  media_volume:

